---
- name: Copy .my.cnf.
  template: src=my.cnf dest=/etc/mysql/my.cnf owner=root mode=0644
  become: yes

- name: Update apt cache.
  apt: update_cache=yes
  become: yes

- name: debconf - set mysql-server password.
  debconf: name=mysql-server-8.0 question=mysql-server/root_password vtype=password value={{db_password}}
  become: yes

- name: debconf - set mysql-server password again.
  debconf: name=mysql-server-8.0 question=mysql-server/root_password_again vtype=password value={{db_password}}
  become: yes

- name: Install mysql-server.
  apt: name=mysql-server-8.0 state=present
  become: yes

- name: Setup local db.
  mysql_db:
    name={{db_name}}
    login_user=root
    login_password={{db_password}}
    login_host={{db_hostname}}
    state=present
    encoding=utf8
    collation=utf8_general_ci
  vars:
    ansible_python_interpreter: /usr/bin/python3